#!/usr/bin/env bash

######################
# clear model and log
######################
rm -rf model/* *.log


######################
# start ps task
######################
python census_wide_n_deep.py --data_dir census-data --model_dir `pwd`/model --ps_hosts localhost:22221 --worker_hosts localhost:22222,localhost:22223 --job_name ps --task_index 0 > /dev/null 2>&1 &


######################
# start worker 0 task
######################
python census_wide_n_deep.py --data_dir census-data --model_dir `pwd`/model --ps_hosts localhost:22221 --worker_hosts localhost:22222,localhost:22223 --job_name worker --task_index 0 > worker_0.log 2>&1 &


######################
# start worker 1 task
######################
python census_wide_n_deep.py --data_dir census-data --model_dir `pwd`/model --ps_hosts localhost:22221 --worker_hosts localhost:22222,localhost:22223 --job_name worker --task_index 1 #> worker_1.log 2>&1 &

