apiVersion: v1
kind: Service
metadata:
  name: tf-worker0
  labels:
    tf-worker: "0"
spec:
  type: ClusterIP
  ports:
  - port: 2222
    targetPort: 2222
  selector:
    tf-worker: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: tf-worker1
  labels:
    tf-worker: "1"
spec:
  type: ClusterIP
  ports:
  - port: 2222
    targetPort: 2222
  selector:
    tf-worker: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: tf-ps0
  labels:
    tf-ps: "0"
spec:
  type: ClusterIP
  ports:
  - port: 2222
    targetPort: 2222
  selector:
    tf-ps: "0"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: tf-worker0
spec:
  template:
    metadata:
      labels:
        tf-worker: "0"
        name-prefix: "tf"
        job: "worker"
    spec:
      restartPolicy: Never
      containers:
      - name: tf-worker0
        image: "dyzhou/tf_wide_n_deep:0.1"
        imagePullPolicy: IfNotPresent
        args: ["--data_dir", "/app/census-data", "--model_dir", "/shared/model", "--ps_hosts", "tf-ps0:2222", "--worker_hosts", "localhost:2222,tf-worker1:2222", "--job_name", "worker", "--task_index", "0"]
        resources:
          requests:
            cpu: "100m"
          limits:
            alpha.kubernetes.io/nvidia-gpu: 0
        ports:
        - containerPort: 2222
        env: []
        volumeMounts: [{name: shared, mountPath: /shared}]
      volumes: [{name: shared, hostPath: {path: /shared}}]
---
apiVersion: batch/v1
kind: Job
metadata:
  name: tf-worker1
spec:
  template:
    metadata:
      labels:
        tf-worker: "1"
        name-prefix: "tf"
        job: "worker"
    spec:
      restartPolicy: Never
      containers:
      - name: tf-worker1
        image: "dyzhou/tf_wide_n_deep:0.1"
        imagePullPolicy: IfNotPresent
        args: ["--data_dir", "/app/census-data", "--model_dir", "/shared/model", "--ps_hosts", "tf-ps0:2222", "--worker_hosts", "tf-worker0:2222,localhost:2222", "--job_name", "worker", "--task_index", "1"]
        resources:
          requests:
            cpu: "100m"
          limits:
            alpha.kubernetes.io/nvidia-gpu: 0
        ports:
        - containerPort: 2222
        env: []
        volumeMounts: [{name: shared, mountPath: /shared}]
      volumes: [{name: shared, hostPath: {path: /shared}}]
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: tf-ps0
spec:
  replicas: 1
  template:
    metadata:
      labels:
        tf-ps: "0"
        name-prefix: "tf"
        job: "ps"
    spec:
      restartPolicy: Always
      containers:
      - name: tf-ps0
        image: "dyzhou/tf_wide_n_deep:0.1"
        imagePullPolicy: IfNotPresent
        args: ["--data_dir", "/app/census-data", "--model_dir", "/shared/model", "--ps_hosts", "tf-ps0:2222", "--worker_hosts", "tf-worker0:2222,tf-worker1:2222", "--job_name", "ps", "--task_index", "0"]
        resources:
          requests:
            cpu: "100m"
        ports:
        - containerPort: 2222
        env: []
        volumeMounts: [{name: shared, mountPath: /shared}]
      volumes: [{name: shared, hostPath: {path: /shared}}]

